CREATE TABLE NUTRICIONISTA (
  CodigoNutricionista  INT NOT NULL,
  Cedula INT NOT NULL,
  Nombre1 VARCHAR(50) NOT NULL,
  Nombre2 VARCHAR(50) NOT NULL,
  Apellido1 VARCHAR(50) NOT NULL,
  Apellido2 VARCHAR(50) ,
  Direccion VARCHAR(100) NOT NULL,
  Foto VARCHAR(50) NOT NULL,
  FechaNacimiento DATE,
  Peso NUMERIC(5,2) NOT NULL,
  Altura NUMERIC(3,2) NOT NULL,
  NumeroTarjetacredito VARCHAR(20) NOT NULL,
  TipoCobro CHAR(50) NOT NULL,
  Correo VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PRIMARY KEY (CodigoNutricionista)
);
CREATE TABLE USUARIO(
  Cedula INT NOT NULL,
  Nombre1 VARCHAR(50) NOT NULL,
  Nombre2 VARCHAR(50) NOT NULL,
  Apellido1 VARCHAR(50) NOT NULL,
  Apellido2 VARCHAR(50) ,
  FechaNacimiento DATE,
  Peso NUMERIC(5,2) NOT NULL,
  Altura NUMERIC(3,2) NOT NULL,
  Pais VARCHAR(100) NOT NULL,
  Correo VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  PorcentajeMusculo INT,
  PorcentajeGrasa INT,
  PRIMARY KEY (Cedula)
);
CREATE TABLE PRODUCTO(
  CodigoDBarras  INT NOT NULL, 
  Nombre VARCHAR(50) NOT NULL,
  Descripcion TEXT ,
  Porcion INT,
  Energia INT,
  Grasa  INT,
  Sodio INT,
  Carbohidratos INT,
  Proteina INT,
  Hierro INT,
  Calcio INT,
  Aprobado INT,
  PRIMARY KEY (CodigoDBarras)
);
CREATE TABLE PLANDCOMIDA(
  IDPlan INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDPlan)

);
CREATE TABLE RECETA(
  IDReceta INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDReceta)
);
CREATE TABLE PUEDE_TENER(
  CodigoNutricionista  INT NOT NULL,
  Cedula INT NOT NULL,
  ChatID INT NOT NULL,
  PRIMARY KEY (CodigoNutricionista,Cedula)
);
CREATE TABLE REGISTRAMEDIDAS(
  Cedula INT NOT NULL,
  Zona VARCHAR(50),
  Medida NUMERIC(5,2),
  FechaRegistro DATETIME NOT NULL,
  PRIMARY KEY (Cedula,FechaRegistro),
);
CREATE TABLE NUTRICIONISTA_PLAN(
  IDPlan INT NOT NULL,
  CodigoNutricionista  INT NOT NULL,
  PRIMARY KEY (IDPlan,CodigoNutricionista)
);
CREATE TABLE PRODUCTOXPLAN(
  IDPlan INT NOT NULL,
  CodigoDBarras  INT NOT NULL,  
  PRIMARY KEY (IDPlan,CodigoDBarras)
);
CREATE TABLE RECETAXPLAN(
  IDPlan INT NOT NULL,
  IDReceta INT NOT NULL,  
  PRIMARY KEY (IDPlan,IDReceta)
);
CREATE TABLE PRODUCTOXRECETA(
  CodigoDBarras  INT NOT NULL,  
  IDReceta INT NOT NULL,  
  PRIMARY KEY (CodigoDBarras,IDReceta)
);
CREATE TABLE PRODUCTO_VITAMINA(
  CodigoDBarras  INT NOT NULL,  
  Vitaminas VARCHAR(50) NOT NULL,  
  PRIMARY KEY (CodigoDBarras,Vitaminas)
);
/*  llaves foraneas a codigoNutricionista*/
/*1*/
ALTER TABLE PUEDE_TENER
ADD CONSTRAINT PUEDE_TENER_NUTRICIONISTA_FK FOREIGN KEY (CodigoNutricionista)
REFERENCES NUTRICIONISTA(CodigoNutricionista);

/*2*/
ALTER TABLE NUTRICIONISTA_PLAN
ADD CONSTRAINT NUTRICIONISTA_PLAN_NUTRICIONISTA_FK FOREIGN KEY (CodigoNutricionista)
REFERENCES NUTRICIONISTA(CodigoNutricionista);


/*  llaves foraneas a cedula (usuario)*/
/*3*/
ALTER TABLE PUEDE_TENER
ADD CONSTRAINT PUEDE_TENER_USUARIO_FK FOREIGN KEY (Cedula)
REFERENCES USUARIO(Cedula);

/*4*/
ALTER TABLE REGISTRAMEDIDAS
ADD CONSTRAINT REGISTRAMEDIDAS_USUARIO_FK FOREIGN KEY (Cedula)
REFERENCES USUARIO(Cedula);

/*  llaves foraneas a IDPlan*/
/*5*/
ALTER TABLE NUTRICIONISTA_PLAN
ADD CONSTRAINT NUTRICIONISTA_PLAN_PLANDCOMIDA_FK FOREIGN KEY (IDPlan)
REFERENCES PLANDCOMIDA(IDPlan);

/*6*/
ALTER TABLE PRODUCTOXPLAN
ADD CONSTRAINT PRODUCTOXPLAN_PLANDCOMIDA_FK FOREIGN KEY (IDPlan)
REFERENCES PLANDCOMIDA(IDPlan);

/*7*/
ALTER TABLE RECETAXPLAN
ADD CONSTRAINT RECETAXPLAN_PLANDCOMIDA_FK FOREIGN KEY (IDPlan)
REFERENCES PLANDCOMIDA(IDPlan);

/*  llaves foraneas a CodigoDBarras*/
/*8*/
ALTER TABLE PRODUCTOXPLAN
ADD CONSTRAINT PRODUCTOXPLAN_PRODUCTO_FK FOREIGN KEY (CodigoDBarras)
REFERENCES PRODUCTO(CodigoDBarras);

/*9*/
ALTER TABLE PRODUCTOXRECETA
ADD CONSTRAINT PRODUCTOXRECETA_PRODUCTO_FK FOREIGN KEY (CodigoDBarras)
REFERENCES PRODUCTO(CodigoDBarras);

/*10*/
ALTER TABLE PRODUCTO_VITAMINA
ADD CONSTRAINT PRODUCTO_VITAMINA_PRODUCTO_FK FOREIGN KEY (CodigoDBarras)
REFERENCES PRODUCTO(CodigoDBarras);

/*  llaves foraneas a IDReceta*/
/*11*/
ALTER TABLE RECETAXPLAN
ADD CONSTRAINT RECETAXPLAN_RECETA_FK FOREIGN KEY (IDReceta)
REFERENCES RECETA(IDReceta);

/*12*/
ALTER TABLE PRODUCTOXRECETA
ADD CONSTRAINT PRODUCTOXRECETA_RECETA_FK FOREIGN KEY (IDReceta)
REFERENCES RECETA(IDReceta);